In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("spam.csv")

In [3]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
 df['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

These both are doing same works

In [6]:
def get_spam_check(x):
    if(x=='spam'):
        return 1
    else:
        return 0

In [7]:
df['spam']=df['Category'].apply(lambda x: 1 if x =='spam' else 0)
# df['spam']=df['Category'].apply(get_spam_check)

In [8]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [9]:
df.shape

(5572, 3)

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['Message'],df['spam'],test_size=.2)

In [11]:
X_train.shape

(4457,)

In [12]:
X_test.shape

(1115,)

In [13]:
type(X_train)

pandas.core.series.Series

In [14]:
X_train[:4]

3363         No messages on her phone. I'm holding it now
4302    Are there TA jobs available? Let me know pleas...
4969    Future is not what we planned for tomorrow.......
2031    Ugh y can't u just apologize, admit u were wro...
Name: Message, dtype: object

In [15]:
X_train[:4][3363]

"No messages on her phone. I'm holding it now"

In [16]:
type(y_train)

pandas.core.series.Series

In [17]:
y_train[:4]

3363    0
4302    0
4969    0
2031    0
Name: spam, dtype: int64

In [21]:
X_train.values

array(["No messages on her phone. I'm holding it now",
       'Are there TA jobs available? Let me know please cos i really need to start working',
       'Future is not what we planned for tomorrow.....! it is the result of what we do today...! Do the best in present... enjoy the future.',
       ..., 'So the sun is anti sleep medicine.',
       'HOT LIVE FANTASIES call now 08707500020 Just 20p per min NTT Ltd, PO Box 1327 Croydon CR9 5WB 0870 is a national rate call',
       'U have a secret admirer who is looking 2 make contact with U-find out who they R*reveal who thinks UR so special-call on 09058094594'],
      dtype=object)

In [22]:
type(X_train.values)

numpy.ndarray

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

v=CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7713 sparse matrix of type '<class 'numpy.int64'>'
	with 58855 stored elements in Compressed Sparse Row format>

In [29]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
X_train_cv.shape
# theses means there aree 4457 eamils and 7713 words in vocabluary

(4457, 7713)

In [33]:
# this give all the words in vocab
v.get_feature_names_out()

array(['00', '000', '008704050406', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [36]:
v.get_feature_names_out()[1000:1050]

array(['anthony', 'anti', 'any', 'anybody', 'anyhow', 'anymore', 'anyone',
       'anyplaces', 'anythin', 'anything', 'anythingtomorrow', 'anytime',
       'anyway', 'anyways', 'anywhere', 'aom', 'apart', 'apartment',
       'apes', 'apeshit', 'aphex', 'apnt', 'apo', 'apologetic',
       'apologise', 'apologize', 'app', 'apparently', 'appeal', 'appear',
       'appendix', 'applausestore', 'applebees', 'apples', 'application',
       'apply', 'applyed', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaching', 'appropriate', 'approve', 'approved',
       'approx', 'apps', 'appt', 'appy', 'april'], dtype=object)

In [37]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',

In [41]:
v.get_feature_names_out()[4782]

'no'

In [38]:
v.vocabulary_

{'no': 4782,
 'messages': 4445,
 'on': 4930,
 'her': 3409,
 'phone': 5189,
 'holding': 3466,
 'it': 3748,
 'now': 4833,
 'are': 1059,
 'there': 6828,
 'ta': 6670,
 'jobs': 3819,
 'available': 1168,
 'let': 4075,
 'me': 4395,
 'know': 3949,
 'please': 5253,
 'cos': 2030,
 'really': 5607,
 'need': 4719,
 'to': 6922,
 'start': 6441,
 'working': 7566,
 'future': 3050,
 'is': 3736,
 'not': 4819,
 'what': 7451,
 'we': 7392,
 'planned': 5239,
 'for': 2934,
 'tomorrow': 6948,
 'the': 6810,
 'result': 5754,
 'of': 4887,
 'do': 2381,
 'today': 6929,
 'best': 1334,
 'in': 3633,
 'present': 5389,
 'enjoy': 2607,
 'ugh': 7103,
 'can': 1644,
 'just': 3864,
 'apologize': 1025,
 'admit': 835,
 'were': 7438,
 'wrong': 7598,
 'and': 972,
 'ask': 1105,
 'take': 6684,
 'back': 1209,
 'host': 3502,
 'based': 1249,
 'idps': 3590,
 'linux': 4123,
 'systems': 6667,
 'knock': 3947,
 'txt': 7081,
 'whose': 7475,
 '80082': 657,
 'enter': 2614,
 'weekly': 7418,
 'draw': 2448,
 '250': 381,
 'gift': 3126,
 'voucher

In [45]:
X_train_np=X_train_cv.toarray()[:4]
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [46]:
np.where(X_train_np[0]!=0)

(array([3409, 3466, 3748, 4445, 4782, 4833, 4930, 5189], dtype=int64),)

In [48]:
X_train[:4][3363]

"No messages on her phone. I'm holding it now"

In [57]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [58]:
X_test_cv=v.transform(X_test)

In [60]:
from sklearn.metrics import classification_report

y_pred=model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       973
           1       0.97      0.96      0.97       142

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [61]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
email_cv=v.transform(emails)
model.predict(email_cv)


array([0, 1], dtype=int64)

# Train the model using sklearn pipeline and reduce number of lines of code

In [67]:
from sklearn.pipeline import Pipeline

clf=Pipeline([
    ('Vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [68]:
clf.fit(X_train,y_train)

Pipeline(steps=[('Vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [73]:
# print(classification_report(y_test,clf.predict(X_test)))

y_pred=clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       973
           1       0.97      0.96      0.97       142

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115

